# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bridegroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone number')),
                ('higher_degree', models.CharField(choices=[('MCA', 'MCA')], max_length=255, verbose_name='Higher Degree')),
                ('occupations', models.CharField(choices=[('Software Developer', 'Software Developer')], max_length=255, verbose_name='Occupations Name')),
                ('gothram', models.CharField(choices=[('Gothram', 'Gothram')], max_length=255, verbose_name='Gothram Name')),
                ('language', models.CharField(choices=[('Tamil', 'Tamil')], max_length=255, verbose_name='Language Name')),
                ('raasi', models.CharField(choices=[('Raasi', 'Raasi')], max_length=255, verbose_name='Raasi Name')),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu')], max_length=255, verbose_name='Religion Name')),
                ('star', models.CharField(choices=[('Stars', 'Stars')], max_length=255, verbose_name='Stars Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Personal Information')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=255, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('height', models.FloatField(verbose_name='Height in CM')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=255, verbose_name='Marital Status')),
                ('physical_status', models.BooleanField(default=False, verbose_name='Physical Status')),
                ('complexion', models.CharField(choices=[('Dark', 'Dark'), ('Wheatish', 'Wheatish'), ('Fair', 'Fair')], max_length=255, verbose_name='Complexion')),
                ('drinking', models.BooleanField(default=False, verbose_name='Drinking ?')),
                ('smoking', models.BooleanField(default=False, verbose_name='Smoking ?')),
                ('employed', models.BooleanField(default=True, verbose_name='Employed ?')),
                ('income', models.FloatField(verbose_name='Annual income')),
                ('display_income', models.BooleanField(default=True, verbose_name='Show Income to all ?')),
                ('display_photo', models.BooleanField(default=True, verbose_name='Show Photo to all ?')),
                ('only_preferred_star', models.BooleanField(default=True, verbose_name='Show only to preferred star ?')),
                ('only_preferred_cast', models.BooleanField(default=True, verbose_name='Show only to preferred cast ?')),
                ('only_preferred_income', models.BooleanField(default=True, verbose_name='Show only to preferred income range ?')),
                ('only_preferred_status', models.BooleanField(default=True, verbose_name='Show only to preferred family status ?')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'db_table': 'occupations',
            },
        ),
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Cast', 'Cast')], max_length=255, verbose_name='Cast Name')),
            ],
            options={
                'verbose_name': 'Cast',
                'verbose_name_plural': 'Casts',
                'db_table': 'casts',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Chennai', 'Chennai')], max_length=255, verbose_name='City Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('India', 'India')], max_length=255, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Rich', 'Rich'), ('Upper Middle', 'Upper Middle'), ('Middle', 'Middle')], max_length=255, verbose_name='status')),
                ('father_name', models.CharField(max_length=255, verbose_name='Father name')),
                ('mother_name', models.CharField(max_length=255, verbose_name='Mother name')),
                ('brother', models.IntegerField(default=1, verbose_name='Elder Brother')),
                ('brother_younger', models.IntegerField(default=1, verbose_name='Younger Brother')),
                ('brother_married', models.IntegerField(default=1, verbose_name='Number of married Brother')),
                ('sister', models.IntegerField(default=1, verbose_name='Elder Sister')),
                ('sister_younger', models.IntegerField(default=1, verbose_name='Younger Sister')),
                ('sister_married', models.IntegerField(default=1, verbose_name='Number of married Sister')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About Family')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Tamil Nadu', 'Tamil Nadu')], max_length=255, verbose_name='State Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State',
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='SubCasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('SubCast', 'SubCast')], max_length=255, verbose_name='SubCast Name')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_casts', to='bridegroom.Casts')),
            ],
            options={
                'verbose_name': 'SubCast',
                'verbose_name_plural': 'SubCasts',
                'db_table': 'subcasts',
            },
        ),
    ]
