# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridegroom', '0002_auto_20160515_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridegroom',
            options={'verbose_name': 'Bride Groom', 'verbose_name_plural': 'Brides Grooms'},
        ),
        migrations.AlterModelTable(
            name='bridegroom',
            table='bridegrooms',
        ),
    ]
