# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridegroom', '0003_auto_20160515_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridegroom',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='bridegroom',
            name='gothram',
        ),
        migrations.RemoveField(
            model_name='bridegroom',
            name='language',
        ),
        migrations.AddField(
            model_name='family',
            name='cast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bridegroom_cast', to='bridegroom.Casts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='gothram',
            field=models.CharField(choices=[('Gothram', 'Gothram')], default=1, max_length=255, verbose_name='Gothram Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='language',
            field=models.CharField(choices=[('Tamil', 'Tamil')], default=1, max_length=255, verbose_name='Language Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='drinking',
            field=models.BooleanField(default=False, verbose_name='Drinking Yes or No ?'),
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='employed',
            field=models.BooleanField(default=True, verbose_name='Employed Yes or No?'),
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='Smoking Yes or No ?'),
        ),
        migrations.AlterField(
            model_name='family',
            name='native_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_city', to='bridegroom.City'),
        ),
    ]
