# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bridegroom', '0004_auto_20160515_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('higher_degree', models.CharField(choices=[('MCA', 'MCA')], max_length=255, verbose_name='Higher Degree')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'db_table': 'educations',
                'verbose_name_plural': 'Educations',
                'verbose_name': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Gothram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Gothram', 'Gothram')], max_length=255, verbose_name='Gothram Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gothram_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gothram_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'db_table': 'gothram',
                'verbose_name_plural': 'Gothrams',
                'verbose_name': 'Gothram',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Tamil', 'Tamil')], max_length=255, verbose_name='Language Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'db_table': 'languages',
                'verbose_name_plural': 'Languages',
                'verbose_name': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Software Developer', 'Software Developer')], max_length=255, verbose_name='Occupations Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupations_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'db_table': 'occupations',
                'verbose_name_plural': 'Occupations',
                'verbose_name': 'Occupation',
            },
        ),
        migrations.CreateModel(
            name='PhoneSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of number viewed')),
            ],
        ),
        migrations.CreateModel(
            name='Raasis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Raasi', 'Raasi')], max_length=255, verbose_name='Raasi Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raasis_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raasis_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'db_table': 'raasis',
                'verbose_name_plural': 'Raasis',
                'verbose_name': 'Raasi',
            },
        ),
        migrations.CreateModel(
            name='Religions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Hindu', 'Hindu')], max_length=255, verbose_name='Religion Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='religions_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='religions_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'db_table': 'religions',
                'verbose_name_plural': 'Religions',
                'verbose_name': 'Religion',
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Stars', 'Stars')], max_length=255, verbose_name='Stars Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars_last_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated by')),
            ],
            options={
                'db_table': 'stars',
                'verbose_name_plural': 'Stars',
                'verbose_name': 'Star',
            },
        ),
        migrations.RemoveField(
            model_name='bridegroom',
            name='religion',
        ),
        migrations.AddField(
            model_name='bridegroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='bridegroom',
            name='phone_number_view_count',
            field=models.PositiveIntegerField(default=100, verbose_name='Number of contacts left till'),
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='higher_degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridegroom_education', to='bridegroom.Educations'),
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='income',
            field=models.FloatField(default=0, verbose_name='Annual income'),
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='occupations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridegroom_occupation', to='bridegroom.Occupations'),
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='raasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridegroom_raasi', to='bridegroom.Raasis'),
        ),
        migrations.AlterField(
            model_name='bridegroom',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridegroom_star', to='bridegroom.Stars'),
        ),
        migrations.AlterField(
            model_name='family',
            name='gothram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_gothram', to='bridegroom.Gothram'),
        ),
        migrations.AlterField(
            model_name='family',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_language', to='bridegroom.Languages'),
        ),
        migrations.AddField(
            model_name='phoneseen',
            name='bridegroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_no_views', to='bridegroom.BrideGroom'),
        ),
        migrations.AddField(
            model_name='phoneseen',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='bridegroom.BrideGroom'),
        ),
        migrations.AddField(
            model_name='family',
            name='religion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='family_religion', to='bridegroom.Religions'),
            preserve_default=False,
        ),
    ]
