# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bridegroom', '0011_auto_20160516_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridegroom',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='bridegroom',
            name='phone_number_view_count',
        ),
        migrations.RemoveField(
            model_name='phoneseen',
            name='bridegroom',
        ),
        migrations.AddField(
            model_name='family',
            name='alternate_phone',
            field=models.CharField(default=1, max_length=25, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='phone_number_view_count',
            field=models.PositiveIntegerField(default=100, verbose_name='Number of contacts left till'),
        ),
        migrations.AddField(
            model_name='phoneseen',
            name='family',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_no_views', to='bridegroom.Family'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phoneseen',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='bridegroom.Family'),
        ),
    ]
