# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridegroom', '0012_auto_20160516_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridegroom',
            old_name='city',
            new_name='living_city',
        ),
        migrations.AlterField(
            model_name='family',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number'),
        ),
    ]
